package db

// schema contains all CREATE TABLE IF NOT EXISTS statements.
// Run in order at startup — idempotent.
var schema = []string{
	`CREATE TABLE IF NOT EXISTS sessions (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		endpoint_url TEXT NOT NULL,
		model TEXT NOT NULL,
		owner TEXT,
		rag INTEGER NOT NULL DEFAULT 0,
		archived INTEGER NOT NULL DEFAULT 0,
		folder TEXT,
		headers TEXT DEFAULT '{}',
		last_accessed DATETIME DEFAULT CURRENT_TIMESTAMP,
		last_message_at DATETIME,
		message_count INTEGER NOT NULL DEFAULT 0,
		is_important INTEGER NOT NULL DEFAULT 0,
		mode TEXT,
		crew_member_id TEXT,
		total_input_tokens INTEGER NOT NULL DEFAULT 0,
		total_output_tokens INTEGER NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_sessions_owner ON sessions(owner)`,
	`CREATE INDEX IF NOT EXISTS ix_sessions_active ON sessions(archived, last_accessed)`,
	`CREATE INDEX IF NOT EXISTS ix_sessions_last_message_at ON sessions(archived, last_message_at)`,

	`CREATE TABLE IF NOT EXISTS chat_messages (
		id TEXT PRIMARY KEY,
		session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
		role TEXT NOT NULL,
		content TEXT NOT NULL,
		metadata TEXT,
		timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_messages_session_time ON chat_messages(session_id, timestamp)`,

	`CREATE TABLE IF NOT EXISTS documents (
		id TEXT PRIMARY KEY,
		session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
		title TEXT NOT NULL DEFAULT 'Untitled',
		language TEXT,
		current_content TEXT NOT NULL DEFAULT '',
		version_count INTEGER NOT NULL DEFAULT 1,
		is_active INTEGER NOT NULL DEFAULT 1,
		archived INTEGER NOT NULL DEFAULT 0,
		owner TEXT,
		tidy_verdict TEXT,
		source_email_uid TEXT,
		source_email_folder TEXT,
		source_email_account_id TEXT,
		source_email_message_id TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_documents_owner ON documents(owner)`,
	`CREATE INDEX IF NOT EXISTS ix_documents_source_email ON documents(source_email_message_id)`,

	`CREATE TABLE IF NOT EXISTS document_versions (
		id TEXT PRIMARY KEY,
		document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
		version_number INTEGER NOT NULL,
		content TEXT NOT NULL,
		summary TEXT,
		source TEXT NOT NULL DEFAULT 'ai',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_doc_versions_doc ON document_versions(document_id)`,

	`CREATE TABLE IF NOT EXISTS gallery_albums (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		cover_id TEXT,
		owner TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_gallery_albums_owner ON gallery_albums(owner)`,

	`CREATE TABLE IF NOT EXISTS gallery_images (
		id TEXT PRIMARY KEY,
		filename TEXT NOT NULL UNIQUE,
		prompt TEXT NOT NULL DEFAULT '',
		model TEXT,
		size TEXT,
		quality TEXT,
		tags TEXT NOT NULL DEFAULT '',
		ai_tags TEXT NOT NULL DEFAULT '',
		session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
		album_id TEXT REFERENCES gallery_albums(id) ON DELETE SET NULL,
		owner TEXT,
		is_active INTEGER NOT NULL DEFAULT 1,
		favorite INTEGER NOT NULL DEFAULT 0,
		file_hash TEXT,
		taken_at DATETIME,
		camera_make TEXT,
		camera_model TEXT,
		gps_lat TEXT,
		gps_lng TEXT,
		width INTEGER,
		height INTEGER,
		file_size INTEGER,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_gallery_images_owner ON gallery_images(owner)`,
	`CREATE INDEX IF NOT EXISTS ix_gallery_images_hash ON gallery_images(file_hash)`,
	`CREATE INDEX IF NOT EXISTS ix_gallery_images_active ON gallery_images(is_active, created_at)`,

	`CREATE TABLE IF NOT EXISTS email_accounts (
		id TEXT PRIMARY KEY,
		owner TEXT,
		name TEXT NOT NULL,
		is_default INTEGER NOT NULL DEFAULT 0,
		enabled INTEGER NOT NULL DEFAULT 1,
		imap_host TEXT NOT NULL DEFAULT '',
		imap_port INTEGER NOT NULL DEFAULT 993,
		imap_user TEXT NOT NULL DEFAULT '',
		imap_password TEXT NOT NULL DEFAULT '',
		imap_starttls INTEGER NOT NULL DEFAULT 1,
		smtp_host TEXT NOT NULL DEFAULT '',
		smtp_port INTEGER NOT NULL DEFAULT 465,
		smtp_user TEXT NOT NULL DEFAULT '',
		smtp_password TEXT NOT NULL DEFAULT '',
		from_address TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_email_accounts_owner ON email_accounts(owner, is_default)`,

	`CREATE TABLE IF NOT EXISTS model_endpoints (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		base_url TEXT NOT NULL,
		api_key TEXT,
		is_enabled INTEGER NOT NULL DEFAULT 1,
		hidden_models TEXT,
		cached_models TEXT,
		model_type TEXT NOT NULL DEFAULT 'llm',
		supports_tools INTEGER,
		owner TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_model_endpoints_owner ON model_endpoints(owner)`,

	`CREATE TABLE IF NOT EXISTS mcp_servers (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		transport TEXT NOT NULL DEFAULT 'stdio',
		command TEXT,
		args TEXT,
		env TEXT,
		url TEXT,
		is_enabled INTEGER NOT NULL DEFAULT 1,
		oauth_config TEXT,
		disabled_tools TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,

	`CREATE TABLE IF NOT EXISTS comparisons (
		id TEXT PRIMARY KEY,
		session_id TEXT,
		owner TEXT,
		prompt TEXT NOT NULL,
		model_a TEXT NOT NULL,
		model_b TEXT NOT NULL,
		endpoint_a TEXT NOT NULL,
		endpoint_b TEXT NOT NULL,
		response_a TEXT,
		response_b TEXT,
		metrics_a TEXT,
		metrics_b TEXT,
		winner TEXT,
		is_blind INTEGER NOT NULL DEFAULT 1,
		blind_mapping TEXT,
		voted_at DATETIME,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_comparisons_owner ON comparisons(owner)`,

	`CREATE TABLE IF NOT EXISTS signatures (
		id TEXT PRIMARY KEY,
		owner TEXT,
		name TEXT NOT NULL DEFAULT 'Signature',
		data_png TEXT NOT NULL,
		width INTEGER,
		height INTEGER,
		svg TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_signatures_owner ON signatures(owner)`,

	`CREATE TABLE IF NOT EXISTS api_tokens (
		id TEXT PRIMARY KEY,
		owner TEXT,
		name TEXT NOT NULL,
		token_hash TEXT NOT NULL,
		token_prefix TEXT NOT NULL,
		scopes TEXT NOT NULL DEFAULT 'chat',
		is_active INTEGER NOT NULL DEFAULT 1,
		last_used_at DATETIME,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_api_tokens_owner ON api_tokens(owner)`,
	`CREATE INDEX IF NOT EXISTS ix_api_tokens_prefix ON api_tokens(token_prefix)`,

	`CREATE TABLE IF NOT EXISTS webhooks (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		url TEXT NOT NULL,
		secret TEXT,
		events TEXT NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		last_triggered_at DATETIME,
		last_status_code INTEGER,
		last_error TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,

	`CREATE TABLE IF NOT EXISTS user_tools (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		description TEXT,
		icon TEXT NOT NULL DEFAULT '',
		html_content TEXT NOT NULL,
		scope TEXT NOT NULL DEFAULT 'global',
		session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
		owner TEXT,
		is_pinned INTEGER NOT NULL DEFAULT 0,
		is_active INTEGER NOT NULL DEFAULT 1,
		version INTEGER NOT NULL DEFAULT 1,
		author TEXT NOT NULL DEFAULT 'ai',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_user_tools_owner ON user_tools(owner)`,

	`CREATE TABLE IF NOT EXISTS user_tool_data (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		tool_id TEXT NOT NULL REFERENCES user_tools(id) ON DELETE CASCADE,
		key TEXT NOT NULL,
		value TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		UNIQUE(tool_id, key)
	)`,

	`CREATE TABLE IF NOT EXISTS crew_members (
		id TEXT PRIMARY KEY,
		owner TEXT,
		name TEXT NOT NULL,
		avatar TEXT,
		user_name TEXT,
		personality TEXT,
		model TEXT,
		endpoint_url TEXT,
		greeting TEXT,
		enabled_tools TEXT,
		session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		sort_order INTEGER NOT NULL DEFAULT 0,
		is_default_assistant INTEGER NOT NULL DEFAULT 0,
		timezone TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_crew_members_owner ON crew_members(owner)`,

	`CREATE TABLE IF NOT EXISTS scheduled_tasks (
		id TEXT PRIMARY KEY,
		owner TEXT,
		name TEXT NOT NULL DEFAULT 'Untitled Task',
		prompt TEXT,
		task_type TEXT NOT NULL DEFAULT 'llm',
		action TEXT,
		schedule TEXT,
		scheduled_time TEXT,
		scheduled_day INTEGER,
		scheduled_date DATETIME,
		trigger_type TEXT NOT NULL DEFAULT 'schedule',
		trigger_event TEXT,
		trigger_count INTEGER,
		trigger_counter INTEGER NOT NULL DEFAULT 0,
		next_run DATETIME,
		last_run DATETIME,
		status TEXT NOT NULL DEFAULT 'active',
		output_target TEXT NOT NULL DEFAULT 'session',
		session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
		model TEXT,
		endpoint_url TEXT,
		run_count INTEGER NOT NULL DEFAULT 0,
		cron_expression TEXT,
		then_task_id TEXT REFERENCES scheduled_tasks(id) ON DELETE SET NULL,
		webhook_token TEXT UNIQUE,
		crew_member_id TEXT,
		character_id TEXT,
		max_steps INTEGER,
		email_results INTEGER NOT NULL DEFAULT 1,
		notifications_enabled INTEGER NOT NULL DEFAULT 1,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_scheduled_tasks_owner ON scheduled_tasks(owner)`,
	`CREATE INDEX IF NOT EXISTS ix_scheduled_tasks_due ON scheduled_tasks(status, next_run)`,
	`CREATE INDEX IF NOT EXISTS ix_scheduled_tasks_event ON scheduled_tasks(trigger_type, trigger_event, status)`,

	`CREATE TABLE IF NOT EXISTS task_runs (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES scheduled_tasks(id) ON DELETE CASCADE,
		started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		finished_at DATETIME,
		status TEXT NOT NULL DEFAULT 'running',
		result TEXT,
		error TEXT,
		tokens_used INTEGER,
		steps TEXT,
		model TEXT
	)`,
	`CREATE INDEX IF NOT EXISTS ix_task_runs_task ON task_runs(task_id, started_at)`,

	`CREATE TABLE IF NOT EXISTS editor_drafts (
		id TEXT PRIMARY KEY,
		owner TEXT,
		name TEXT NOT NULL DEFAULT 'Untitled',
		source_image_id TEXT,
		width INTEGER,
		height INTEGER,
		payload TEXT NOT NULL DEFAULT '',
		thumbnail TEXT,
		is_active INTEGER NOT NULL DEFAULT 1,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_editor_drafts_owner ON editor_drafts(owner, is_active, updated_at)`,

	`CREATE TABLE IF NOT EXISTS memories (
		id TEXT PRIMARY KEY,
		text TEXT NOT NULL,
		category TEXT NOT NULL DEFAULT 'fact',
		source TEXT NOT NULL DEFAULT 'user',
		owner TEXT,
		session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
		timestamp INTEGER NOT NULL DEFAULT (strftime('%s','now'))
	)`,
	`CREATE INDEX IF NOT EXISTS ix_memories_owner ON memories(owner)`,
	`CREATE INDEX IF NOT EXISTS ix_memories_lookup ON memories(category, timestamp)`,

	`CREATE TABLE IF NOT EXISTS notes (
		id TEXT PRIMARY KEY,
		owner TEXT,
		title TEXT NOT NULL DEFAULT '',
		content TEXT,
		items TEXT,
		note_type TEXT NOT NULL DEFAULT 'note',
		color TEXT,
		label TEXT,
		pinned INTEGER NOT NULL DEFAULT 0,
		archived INTEGER NOT NULL DEFAULT 0,
		due_date TEXT,
		source TEXT NOT NULL DEFAULT 'user',
		session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
		image_url TEXT,
		repeat TEXT NOT NULL DEFAULT 'none',
		sort_order INTEGER,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_notes_owner ON notes(owner)`,

	`CREATE TABLE IF NOT EXISTS calendar_cals (
		id TEXT PRIMARY KEY,
		owner TEXT,
		name TEXT NOT NULL,
		color TEXT NOT NULL DEFAULT '#4A90D9',
		source TEXT NOT NULL DEFAULT 'local',
		remote_url TEXT,
		is_visible INTEGER NOT NULL DEFAULT 1,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_calendar_cals_owner ON calendar_cals(owner)`,

	`CREATE TABLE IF NOT EXISTS calendar_events (
		id TEXT PRIMARY KEY,
		uid TEXT NOT NULL,
		calendar_id TEXT NOT NULL REFERENCES calendar_cals(id) ON DELETE CASCADE,
		title TEXT NOT NULL,
		description TEXT,
		location TEXT,
		start_time DATETIME NOT NULL,
		end_time DATETIME NOT NULL,
		all_day INTEGER NOT NULL DEFAULT 0,
		rrule TEXT,
		is_utc INTEGER NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS ix_calendar_events_cal ON calendar_events(calendar_id)`,
	`CREATE INDEX IF NOT EXISTS ix_calendar_events_uid ON calendar_events(uid)`,
	`CREATE INDEX IF NOT EXISTS ix_calendar_events_time ON calendar_events(start_time, end_time)`,
	`ALTER TABLE memories ADD COLUMN pinned INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE gallery_images ADD COLUMN ai_tags TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE sessions ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0`,
}
